version: '3'
services:
  nest-postgres-posts:
    image: postgres:16
    container_name: nest-postgres
    restart: always
    ports:
     - '5432:5432'
    env_file:
      - .env
    volumes:
      - nest-postgres:/var/lib/postgresql/data

volumes:
  nest-postgres-posts:
    name: nest-postgresql-db